[package]
name = "autopkg-value"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
native-plist = { package = "plist", version = "1" }
indexmap = { version = "2", features = ["serde"] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_json = "1"
serde_yaml = "0.9"
