[workspace]
members = ["crates/value", "crates/cli", "crates/engine", "crates/processors", "crates/platform", "crates/munki", "crates/helpers", "crates/fs", "crates/ditto", "crates/hdiutil", "crates/xar", "crates/pkgutil", "crates/installer", "crates/codesign", "crates/mkbom", "crates/pkgbuild", "crates/aa", "xtask"]
exclude = ["vendor/fancy-regex", "vendor/udif", "vendor/hfsplus", "vendor/apfs", "fuzz"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
