[package]
name = "autopkg-munki"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
plist = { package = "autopkg-value", path = "../value" }
autopkg-platform = { path = "../platform" }
md-5 = "0.11"
sha2 = "0.11"
serde_json = "1"
roxmltree = "0.21"
tempfile = "3"
regex = "1"
encoding_rs = "0.8"

[target.'cfg(unix)'.dependencies]
russet-hdiutil = { path = "../hdiutil" }
russet-installer = { path = "../installer" }
russet-xar = { path = "../xar" }
russet-fs = { path = "../fs" }
russet-mkbom = { path = "../mkbom" }
russet-ditto = { path = "../ditto" }
russet-pkgutil = { path = "../pkgutil" }
icns = "0.5"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation-sys = "0.8"

[target.'cfg(unix)'.dev-dependencies]
russet-pkgbuild = { path = "../pkgbuild" }
png = "0.18"
